### ISSUE TITLE
Support rules based sampling

### ISSUE THREAD

**Issue by shukla2112** [Vlaaaaaaad/terraform-aws-fargate-refinery#8]
Currently, refinery provides an option to define the rules-based sampling. 
From the code, it seems we can't define the rules as part of `terraform.tfvars`

## Description
  What are you trying to do?
  Define the rules based sampling for refinery `rules.toml`
  
  What do you want to do differently?
  As of now, the rules provisioning and expected naming convention is not supported

  What is not supported?
  Defining the rules as part of `terraform.tfvars`
  
  What is frustrating you?
  nothing as such

## Desired solution

  What would you like to happen?
  Able to define the set of rules for sampling the honeycomb log events
  
  How does an ideal flow look like?
  define rules in `terraform.tfvars` -> parse the rules properly under `rules.toml.tpl` and generate the valid `rules.toml`
  
  How should this be implemented?
  Have some basic work done here - https://github.com/Vlaaaaaaad/terraform-aws-fargate-refinery/compare/main...shukla2112:rules-config-support?expand=1

## Notes
  Anything else to add?
  Let me know if there is a way to define rules, I tried to look through the code and concluded that rules are not yet supported.
  Please look at the forked changes. I can work on it to make it more inclusive.

**Comment by Vlaaaaaaad** [comment]
AHA! There are users for this module! I didn't see any usage so I kind of let this rot until I needed it.

This module was written for an older Terraform version and for a very old, pre-1.0 version of Honeycomb's Refinery. I wanted to update it for a while, but it was low on my priority list.

Now that I know there are folks using this, I'll want to fix both of the above by... say Monday, August 19.

@shukla2112 regarding config and rules: the logic around the rules is getting pretty weird and complex. I am thinking of maybe just accepting a path to the `toml` files and just using that. I think that would be more flexible and offload a lot of unnecessary complexity. What do you think about that? Would that work with your usecase?

**Comment by shukla2112** [comment]
@Vlaaaaaaad -  make sense. accepting toml files would simplify by large for the users. Let me know if I can help you anyway.

**Comment by Vlaaaaaaad** [comment]
@shukla2112 [v0.3.0](https://github.com/Vlaaaaaaad/terraform-aws-fargate-refinery/releases/tag/v0.3.0) was just released! It has all the changes we discussed above. I tested it and it works, but it was not very intense testing. Let me know if you discover any bugs!
